In [23]:
import torch
import numpy as np

### One dataset with one tensor

In [24]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])
a = torch.Tensor(a)
print(a.shape)
a_dset = torch.utils.data.TensorDataset(a)
print(a_dset[1])
a_dl = torch.utils.data.DataLoader(a_dset, batch_size=2)
print(next(iter(a_dl)))

torch.Size([4, 3])
(tensor([4., 5., 6.]),)
[tensor([[1., 2., 3.],
        [4., 5., 6.]])]


### One dataset with more than one tensor

In [25]:
b = np.array([[11],
              [22],
              [33],
              [44]])
b = torch.Tensor(b)
print(b.shape)
ab_dset = torch.utils.data.TensorDataset(a,b)
print(ab_dset[1])
ab_dl = torch.utils.data.DataLoader(ab_dset, batch_size=2)
x,y = next(iter(ab_dl))
print(x)


torch.Size([4, 1])
(tensor([4., 5., 6.]), tensor([22.]))
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Concat dataset testing

In [26]:
c = torch.Tensor([[13, 14, 15],
              [16, 17, 18],
              [19, 20, 21],
              [22, 23, 24]])
print(c.shape)
d = torch.Tensor([[55],
                  [66],
                  [77],
                  [88]])
print(d.shape)
cd_dset = torch.utils.data.TensorDataset(c,d)

abcd_dset = torch.utils.data.ConcatDataset([ab_dset, cd_dset])  # tensor takes n arguments but concat takes an iterable...
print(abcd_dset[5])


torch.Size([4, 3])
torch.Size([4, 1])
(tensor([16., 17., 18.]), tensor([66.]))


### Shuffling concat dataset using dataloader with batch = entire dataset

In [27]:
abcd_len = len(abcd_dset)  # for TensorDataset is the shared first dimension
abcd_dl = torch.utils.data.DataLoader(abcd_dset, batch_size=abcd_len, shuffle=True) 
X,y = next(iter(abcd_dl))
print(y)

tensor([[44.],
        [88.],
        [55.],
        [33.],
        [77.],
        [66.],
        [22.],
        [11.]])
