In [1]:
import sys
sys.path.append('/tigress/kendrab/python_pkgs')

import numpy as np
import math
import pyspedas
import pytplot

import mms_structure_finder.curlometer_basic as cb

In [2]:
# get the data and interpolate the correct distances
for i in range(1,5):
    pyspedas.mms.fgm(probe=str(i), trange=['2019-09-27/12-47-00', '2019-09-27/18-55-30'], data_rate='brst',
                     time_clip=True)
    pyspedas.mms.mec(probe=str(i), trange=['2019-09-27/12-47-00', '2019-09-27/18-55-30'], data_rate='brst',
                     time_clip=True)
    # interpolate the mec data to the b data
    pyspedas.tinterpol(f'mms{i}_mec_r_gse', f'mms{i}_fgm_b_gse_brst_l2', method='linear',
                       newname=f'mms{i}_fgm_r_gse_brst_l2')

Loading pydata/mms1/fgm/brst/l2/2019/09/27/mms1_fgm_brst_l2_20190927075943_v5.209.0.cdf
Loading pydata/mms1/fgm/brst/l2/2019/09/27/mms1_fgm_brst_l2_20190927080203_v5.209.0.cdf
Loading pydata/mms1/fgm/brst/l2/2019/09/27/mms1_fgm_brst_l2_20190927083143_v5.209.0.cdf
Loading pydata/mms1/fgm/brst/l2/2019/09/27/mms1_fgm_brst_l2_20190927083413_v5.209.0.cdf
Loading pydata/mms1/fgm/brst/l2/2019/09/27/mms1_fgm_brst_l2_20190927102303_v5.209.0.cdf
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Loaded variables:
Epoch
mms1_fgm_b_gse_brst_l2
mms1_fgm_b_gsm_brst_l2
mms1_fgm_b_dmpa_brst_l2
mms1_fgm_b_bcs_brst_l2
mms1_fgm_flag_brst_l2
Epoch_state
mms1_fgm_hirange_br

01-Sep-23 10:14:23: /home/kendrab/.conda/envs/pyspedas/lib/python3.7/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")



tinterpol (linear) was applied to: mms1_fgm_r_gse_brst_l2
Loading pydata/mms2/fgm/brst/l2/2019/09/27/mms2_fgm_brst_l2_20190927102303_v5.209.0.cdf
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Loaded variables:
Epoch
mms2_fgm_b_gse_brst_l2
mms2_fgm_b_gsm_brst_l2
mms2_fgm_b_dmpa_brst_l2
mms2_fgm_b_bcs_brst_l2
mms2_fgm_flag_brst_l2
Epoch_state
mms2_fgm_hirange_brst_l2
mms2_fgm_bdeltahalf_brst_l2
mms2_fgm_stemp_brst_l2
mms2_fgm_etemp_brst_l2
mms2_fgm_mode_brst_l2
mms2_fgm_rdeltahalf_brst_l2
mms2_fgm_b_dmpa_brst_l2_bvec
mms2_fgm_b_dmpa_brst_l2_btot
mms2_fgm_b_gse_brst_l2_bvec
mms2_fgm_b_gse_brst_l2_btot
mms2_fgm_b_gsm_brst_l2_bvec
mms2_fgm_b_gsm_brst_l2

01-Sep-23 10:14:35: /home/kendrab/.conda/envs/pyspedas/lib/python3.7/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")



tinterpol (linear) was applied to: mms2_fgm_r_gse_brst_l2
Loading pydata/mms3/fgm/brst/l2/2019/09/27/mms3_fgm_brst_l2_20190927102303_v5.209.0.cdf
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Loaded variables:
Epoch
mms3_fgm_b_gse_brst_l2
mms3_fgm_b_gsm_brst_l2
mms3_fgm_b_dmpa_brst_l2
mms3_fgm_b_bcs_brst_l2
mms3_fgm_flag_brst_l2
Epoch_state
mms3_fgm_hirange_brst_l2
mms3_fgm_bdeltahalf_brst_l2
mms3_fgm_stemp_brst_l2
mms3_fgm_etemp_brst_l2
mms3_fgm_mode_brst_l2
mms3_fgm_rdeltahalf_brst_l2
mms3_fgm_b_dmpa_brst_l2_bvec
mms3_fgm_b_dmpa_brst_l2_btot
mms3_fgm_b_gse_brst_l2_bvec
mms3_fgm_b_gse_brst_l2_btot
mms3_fgm_b_gsm_brst_l2_bvec
mms3_fgm_b_gsm_brst_l2

01-Sep-23 10:14:45: /home/kendrab/.conda/envs/pyspedas/lib/python3.7/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")



tinterpol (linear) was applied to: mms3_fgm_r_gse_brst_l2
Loading pydata/mms4/fgm/brst/l2/2019/09/27/mms4_fgm_brst_l2_20190927102303_v5.209.0.cdf
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Time clip returns empty data.
Loaded variables:
Epoch
mms4_fgm_b_gse_brst_l2
mms4_fgm_b_gsm_brst_l2
mms4_fgm_b_dmpa_brst_l2
mms4_fgm_b_bcs_brst_l2
mms4_fgm_flag_brst_l2
Epoch_state
mms4_fgm_hirange_brst_l2
mms4_fgm_bdeltahalf_brst_l2
mms4_fgm_stemp_brst_l2
mms4_fgm_etemp_brst_l2
mms4_fgm_mode_brst_l2
mms4_fgm_rdeltahalf_brst_l2
mms4_fgm_b_dmpa_brst_l2_bvec
mms4_fgm_b_dmpa_brst_l2_btot
mms4_fgm_b_gse_brst_l2_bvec
mms4_fgm_b_gse_brst_l2_btot
mms4_fgm_b_gsm_brst_l2_bvec
mms4_fgm_b_gsm_brst_l2

01-Sep-23 10:14:55: /home/kendrab/.conda/envs/pyspedas/lib/python3.7/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")



tinterpol (linear) was applied to: mms4_fgm_r_gse_brst_l2


In [3]:
# check for nans
for i in range(1,5):
    print(pytplot.data_quants[f'mms{i}_fgm_b_gse_brst_l2'][0:50])
    print(pytplot.data_quants[f'mms{i}_mec_r_gse'])

<xarray.DataArray 'mms1_fgm_b_gse_brst_l2' (time: 50, v_dim: 4)>
array([[-26.66934  ,   1.8911977,   3.983162 ,  27.031387 ],
       [-26.649662 ,   1.8852147,   3.9968984,  27.013582 ],
       [-26.66898  ,   1.8888326,   4.011724 ,  27.03509  ],
       [-26.667934 ,   1.8726981,   3.9875493,  27.02936  ],
       [-26.67062  ,   1.8784366,   3.9928803,  27.033194 ],
       [-26.72015  ,   1.8991671,   3.9742012,  27.08076  ],
       [-26.740498 ,   1.8971677,   3.979325 ,  27.101448 ],
       [-26.723307 ,   1.8922243,   4.0139055,  27.089243 ],
       [-26.720934 ,   1.9032754,   4.0018997,  27.085897 ],
       [-26.70213  ,   1.8984897,   4.007154 ,  27.06779  ],
       [-26.702387 ,   1.8990581,   4.0086675,  27.068308 ],
       [-26.702202 ,   1.8944286,   4.0162287,  27.068922 ],
       [-26.728155 ,   1.8946077,   4.0192447,  27.094982 ],
       [-26.716568 ,   1.9045767,   4.032262 ,  27.086187 ],
       [-26.704596 ,   1.9164206,   4.058656 ,  27.079157 ],
       [-26.738548 ,

In [4]:
#pyspedas version
pyspedas.mms.curlometer(fields=[f'mms{i}_fgm_b_gse_brst_l2' for i in range(1,5)],
                        positions=[f'mms{i}_mec_r_gse' for i in range(1,5)])

01-Sep-23 10:14:55: /home/kendrab/.conda/envs/pyspedas/lib/python3.7/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")



tinterpol (linear) was applied to: mms2_fgm_b_gse_brst_l2_i


01-Sep-23 10:14:55: /home/kendrab/.conda/envs/pyspedas/lib/python3.7/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")



tinterpol (linear) was applied to: mms3_fgm_b_gse_brst_l2_i


01-Sep-23 10:14:55: /home/kendrab/.conda/envs/pyspedas/lib/python3.7/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")



tinterpol (linear) was applied to: mms4_fgm_b_gse_brst_l2_i


01-Sep-23 10:14:55: /home/kendrab/.conda/envs/pyspedas/lib/python3.7/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")



tinterpol (linear) was applied to: mms1_mec_r_gse_i


01-Sep-23 10:14:55: /home/kendrab/.conda/envs/pyspedas/lib/python3.7/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")



tinterpol (linear) was applied to: mms2_mec_r_gse_i


01-Sep-23 10:14:55: /home/kendrab/.conda/envs/pyspedas/lib/python3.7/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")



tinterpol (linear) was applied to: mms3_mec_r_gse_i


01-Sep-23 10:14:55: /home/kendrab/.conda/envs/pyspedas/lib/python3.7/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")



tinterpol (linear) was applied to: mms4_mec_r_gse_i


['baryb', 'curlB', 'divB', 'jtotal', 'jpar', 'jperp', 'alpha', 'alphaparallel']

In [5]:
# sync to common timeline
for i in range(1,5):
    pytplot.data_quants[f'mms{i}_fgm_b_gse_brst_l2'] = \
        pytplot.data_quants[f'mms{i}_fgm_b_gse_brst_l2'].interp(method="linear", assume_sorted=False,
                                                                time=pytplot.data_quants["mms1_fgm_b_gse_brst_l2"].time)
    pytplot.data_quants[f'mms{i}_fgm_r_gse_brst_l2'] = \
        pytplot.data_quants[f'mms{i}_fgm_r_gse_brst_l2'].interp(method="linear", assume_sorted=False,
                                                                time=pytplot.data_quants["mms1_fgm_b_gse_brst_l2"].time)

01-Sep-23 10:15:30: /home/kendrab/.conda/envs/pyspedas/lib/python3.7/site-packages/xarray/core/pycompat.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  duck_array_version = LooseVersion("0.0.0")



In [6]:
# check shapes
for i in range(1,5):
    print(pytplot.data_quants[f'mms{i}_fgm_b_gse_brst_l2'].shape)
    print(pytplot.data_quants[f'mms{i}_fgm_r_gse_brst_l2'].shape)

(81536, 4)
(81536, 3)
(81536, 4)
(81536, 3)
(81536, 4)
(81536, 3)
(81536, 4)
(81536, 3)


In [7]:
# package everything up
m=[]

for i in range(1,5):
    m_i = [pytplot.data_quants[f"mms{i}_fgm_b_gse_brst_l2"][:,j] for j in range(0,3)] + [pytplot.data_quants[f"mms{i}_fgm_r_gse_brst_l2"][:,j] for j in range(0,3)]
    print(len(m_i[0]))
    m.append(m_i)

81536
81536
81536
81536


In [8]:
j, divb, divbcurlb = cb.curlometer_vec(m[0], m[1], m[2], m[3])

(81536, 3)
(81536, 3, 3)
(81536,)
(81536, 3)
(81536, 3)


In [11]:
clean_idxs = ~np.isnan(j).any(axis=1)
print(j[clean_idxs].shape)
print(j[clean_idxs])
print(pytplot.data_quants['jtotal'][clean_idxs])

(81265, 3)
[[-2.80026441e-08 -5.32091145e-09  5.46066547e-09]
 [-2.72917390e-08 -6.44121917e-09  4.37098696e-09]
 [-2.68459310e-08 -6.90561526e-09  3.82895509e-09]
 ...
 [-3.89335994e-09  1.22409364e-09 -1.75804421e-09]
 [-3.46739800e-09  9.48539398e-10 -2.79497074e-09]
 [-3.90770991e-09  1.28332901e-09 -1.70851248e-09]]
<xarray.DataArray 'jtotal' (time: 81265, v_dim: 3)>
array([[-2.80026441e-08, -5.32091145e-09,  5.46066547e-09],
       [-2.72917390e-08, -6.44121917e-09,  4.37098696e-09],
       [-2.68459310e-08, -6.90561526e-09,  3.82895509e-09],
       ...,
       [-3.89335994e-09,  1.22409364e-09, -1.75804421e-09],
       [-3.46739800e-09,  9.48539398e-10, -2.79497074e-09],
       [-3.90770990e-09,  1.28332901e-09, -1.70851248e-09]])
Coordinates:
  * time     (time) datetime64[ns] 2019-09-27T07:59:45.012115 ... 2019-09-27T...
Dimensions without coordinates: v_dim
Attributes:
    plot_options:  {'xaxis_opt': {'axis_label': 'Time', 'crosshair': 'X', 'x_...
